In [2]:
# import

import numpy as np

# 从list创建数组

In [120]:
# 从列表list创建一维数组
x = np.array([1,2,3,4])
print(x)
print(x.shape)
print(type(x))
print(type(x[0]))
                

# 指定数组元素数据类型 (numpy的数组的类型必须一致)
x = np.array([1,2,3,4], dtype="float32")
print(x)
print(x[0])
print(type(x[0]))

# 从列表创建二维数组
x = np.array([
    [1,2],
    [3,4],
    [5,6]
])
x


[1 2 3 4]
(4,)
<class 'numpy.ndarray'>
<class 'numpy.int64'>
[1. 2. 3. 4.]
1.0
<class 'numpy.float32'>


array([[1, 2],
       [3, 4],
       [5, 6]])

# 从无到有创建数组

In [121]:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>     创建固定值的数组 / 特殊数组

# 创建长度为5, 值为0的数组
x = np.zeros(shape=(3,2), dtype=int)
print(x)


# 创建一个2*4的浮点型数组, 值都为1
x = np.ones(shape=(2, 4), dtype=float)
print(x)

        
# 创建一个3*5的数组, 值都是8
x = np.full(shape=(3,5), fill_value=8)
print(x)

            
# 创建一个3*3的单位矩阵
x = np.eye(3)
print(x)

            

[[0 0]
 [0 0]
 [0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [122]:

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 1-D数组
            
# 创建一个线性的序列数组: [1, 15), 步长为2
x = np.arange(start=1, stop=15, step=2, dtype=float)
print(x)                            


# 创建一个等差数列: 4个元素, 将[0,1]等分成三份
x = np.linspace(start=0, stop=1, num=4)
print(x)  
    
# 创建一个等比数列, 从10^0 - 10^9次方, 等比的产生10个数
x = np.logspace(start=0, stop=9, num=10, base=10.0)
print(x)
    
    
    
    
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 多维数组
    
# 创建一个3*3数组, 元素为[0.0, 1.0)之间的均匀分布的随机数
x = np.random.random(size=(3,3))
print(x)
            
# 创建一个3*3的数组, 元素为均值为0, 标准差为1的正态分布随机数
x = np.random.normal(loc=0, scale=1, size=(3,3))
print(x)

            
# 创建一个3*3的数组, 元素的取值是[0-10)的随机整数
np.random.randint(low=0, high=10, size=(3, 3))
# 创建一个3*3的数组, 元素的取值是[0-10)的随机整数
np.random.randint(low=10, size=(3,3))
            
            

[ 1.  3.  5.  7.  9. 11. 13.]
[0.         0.33333333 0.66666667 1.        ]
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]
[[0.74040096 0.50207734 0.2373064 ]
 [0.54830478 0.56533944 0.0184281 ]
 [0.93896216 0.57841337 0.48266576]]
[[-2.61472708  0.02406703  0.2103393 ]
 [-0.45958097  1.51445675  0.02513159]
 [ 0.2455094  -1.45162017  0.75455836]]


array([[3, 7, 3],
       [0, 9, 1],
       [0, 5, 0]])

In [123]:
# 将列表进行随机重排列
x = np.array([1,2,3,4])
np.random.permutation(x)
                                    # array([2, 1, 3, 4])
print(x)                            # [1 2 3 4] # permutation不会改变原数组


np.random.shuffle(x)
print(x)                            # [3 1 4 2] # shuffle会改变原数组



[1 2 3 4]
[1 4 3 2]


In [124]:
# 从数组中随机采样
x = np.arange(10, 25, dtype=float)
# 从1-D数组中进行采样, 采样4*3=12次, 构成一个4*3的数组
np.random.choice(x, size=(4,3))
                                    # array([[16., 13., 23.],
                                    #        [22., 23., 14.],
                                    #        [17., 24., 22.],
                                    #        [23., 18., 20.]])
# 针对1-D数组中的采样, 同时设置1-D数组中个元素的的采样概率
np.random.choice(x, size=(4, 3), p=x/np.sum(x))
                                    # array([[16., 15., 15.],
                                    #        [11., 22., 22.],
                                    #        [13., 20., 14.],
                                    #        [13., 22., 22.]])

array([[14., 15., 14.],
       [13., 20., 14.],
       [21., 10., 22.],
       [12., 18., 17.]])

# numpy数组的性质

In [125]:
# ∵ high=None, 此时的取值就是[0, low)之间的整数
x = np.random.randint(low=10,high=None, size=(4,3))
x

array([[6, 5, 3],
       [6, 8, 9],
       [3, 5, 1],
       [4, 2, 7]])

In [126]:
# 数组的性状
x.shape

(4, 3)

In [127]:
# 数组的维度
x.ndim

2

In [128]:
# 数组的大小(元素个数)
x.size

12

In [129]:
# 数组的元素类型
x.dtype

dtype('int64')

# 数组索引

In [130]:
x = np.random.randint(0, 10, size=(3,2))
x

array([[7, 9],
       [7, 3],
       [2, 3]])

In [131]:
x[0][1]

9

In [132]:
# 利用索引进行赋值
# NOTE: 因为数据的元素唯一, 所以会隐式转为为相应的dtype
x[0][0] = 1.67 # 向下取整
x

array([[1, 9],
       [7, 3],
       [2, 3]])

# 数组的切片

## 1-dim 数组

In [133]:
x = np.arange(10)

In [134]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
x[:3]

array([0, 1, 2])

In [136]:
# 逆序
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 多维数组

In [137]:
x = np.random.randint(0, 10, size=(3,4))
x

array([[4, 1, 1, 8],
       [1, 3, 8, 9],
       [7, 0, 3, 0]])

In [138]:
x[:2, :3] # 需要有两个切片操作, 前两行, 前3列

array([[4, 1, 1],
       [1, 3, 8]])

In [139]:
# 行逆序, 列也逆序
x[::-1, ::-1]

array([[0, 3, 0, 7],
       [9, 8, 3, 1],
       [8, 1, 1, 4]])

In [140]:
# 取行
x[1, :] # 取第二行, 0开始
x[1] # 简写

array([1, 3, 8, 9])

In [141]:
# 取列
x[:, 1] # 去第二列

array([1, 3, 0])

### NOTE: 切片默认是视图, 而不是副本, 会修改原数组

In [142]:
x = np.random.randint(0, 10, size=(3,4))
x

array([[3, 8, 8, 1],
       [4, 0, 9, 3],
       [4, 0, 3, 2]])

In [143]:
y = x[0] # 取第0行
y

array([3, 8, 8, 1])

In [144]:
y[0] = 100
x # x[0][0] 跟着改变了!!

array([[100,   8,   8,   1],
       [  4,   0,   9,   3],
       [  4,   0,   3,   2]])

###  如果要获取切片副本, 要用copy函数

In [145]:
x = np.random.randint(0, 100, (3, 2))
x

array([[ 5,  8],
       [11, 97],
       [40, 82]])

In [146]:
y = x[0, :].copy() # y为切片副本
y[0] = 1000
y

array([1000,    8])

In [147]:
x # x不变

array([[ 5,  8],
       [11, 97],
       [40, 82]])

# 数组的变形(视图, 而非副本)

In [148]:
x = np.random.randint(0, 10, (12))
x

array([5, 4, 6, 9, 1, 9, 8, 2, 0, 3, 0, 5])

In [149]:
x.shape # 1-dim数组

(12,)

In [150]:
x1 = x.reshape(3,4)
x1

array([[5, 4, 6, 9],
       [1, 9, 8, 2],
       [0, 3, 0, 5]])

In [151]:
## 1-dim 数组 ==> 转置 (2-dim行向量)

x2 = x.reshape(1, x.shape[0])
x2 # 行向量

x3 = x[np.newaxis, :]
x3 # 行向量


## 1-dim 数组 ==> 转置 (2-dim列向量)

x2 = x.reshape(x.shape[0], 1)
x2 # 列向量

x3 = x[:, np.newaxis]
x3 # 列向量

array([[5],
       [4],
       [6],
       [9],
       [1],
       [9],
       [8],
       [2],
       [0],
       [3],
       [0],
       [5]])

## np.newaxis的用法

[stack-overflow](https://stackoverflow.com/questions/29241056/how-does-numpy-newaxis-work-and-when-to-use-it)

**Scenario: convert 1-dim to Row Vector or Column Vector**

In [152]:
x = np.arange(10)
x.shape

(10,)

In [153]:
# convert x (1-dim) to Row Vector (2-dim)
row_vector = x[np.newaxis, :]
print(row_vector)

print(row_vector.shape)

[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)


In [154]:
# convert x (2-dim) to Column Vector(2-dim)
column_vector = x[:, np.newaxis]

print(column_vector)
print(column_vector.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


## 多维数组转1-dim数组

In [155]:
x = np.random.randint(0, 10, size=(3,2))
x

array([[2, 1],
       [6, 1],
       [6, 2]])

In [156]:
# flattern 返回的是副本

x2 = x.flatten()
x2

array([2, 1, 6, 1, 6, 2])

In [157]:
# ravel 返回的是视图
x3 = x.flatten()
x3

array([2, 1, 6, 1, 6, 2])

In [158]:
# reshape 返回的是视图
x4 = x.reshape(-1)
x4

array([2, 1, 6, 1, 6, 2])

## 数组拼接

In [159]:
x1 = np.array(
[[1,2,3,4],
 [5,6,7,8]])

x2 = np.array([
    [4,3,2,1],
    [9,8,7,6]])

### 水平拼接

In [160]:
# hstack 返回的是副本
x3 = np.hstack([x1, x2])
x3

array([[1, 2, 3, 4, 4, 3, 2, 1],
       [5, 6, 7, 8, 9, 8, 7, 6]])

In [161]:
# c_ 同样也是返回副本
x4 = np.c_[x1, x2]
x4

array([[1, 2, 3, 4, 4, 3, 2, 1],
       [5, 6, 7, 8, 9, 8, 7, 6]])

###  垂直拼接

In [162]:
# 副本
x5 = np.vstack([x1, x2])
x5

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 3, 2, 1],
       [9, 8, 7, 6]])

In [163]:
# 副本
x6 = np.r_[x1, x2]
x6

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 3, 2, 1],
       [9, 8, 7, 6]])

##  数组的分裂

### 一维数组分割

In [173]:
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [175]:
# split array by index list
x2, x3, x4 = np.split(x, [4, 9])
x2, x3, x4

(array([10, 11, 12, 13]), array([14, 15, 16, 17, 18]), array([19]))

### 二维数组的水平分割

In [177]:
x = np.random.randint(0, 10, size=(2, 5))
x

array([[5, 2, 5, 7, 2],
       [5, 6, 2, 2, 1]])

In [179]:
x2, x3, x4 = np.hsplit(x, [1, 3])
x2, x3, x4

(array([[5],
        [5]]),
 array([[2, 5],
        [6, 2]]),
 array([[7, 2],
        [2, 1]]))

##  二维数组的垂直分割

In [180]:
x = np.arange(0, 15).reshape(5, 3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [181]:
x2, x3, x4 = np.vsplit(x, [1, 3])
x2, x3, x4

(array([[0, 1, 2]]),
 array([[3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14]]))

# numpy 运算

## 向量化运算

### 与向量的加减乘除

In [3]:
x1 = np.arange(1, 6)
x1

array([1, 2, 3, 4, 5])

In [4]:
print(x1 + 5)
print(x1 / 5)

[ 6  7  8  9 10]
[0.2 0.4 0.6 0.8 1. ]


In [6]:
print(-x1)
print(x1**2)
print(x1//2) # 整数商
print(x1%2)  # 余数

[-1 -2 -3 -4 -5]
[ 1  4  9 16 25]
[0 1 1 2 2]
[1 0 1 0 1]


In [15]:
### 绝对值

In [10]:
x = np.arange(-2, 2)
print(x)

# abs
np.abs(x)

[-2 -1  0  1]


array([2, 1, 0, 1])

### 三角函数


In [11]:
x = np.linspace(0, np.pi, 3) # [0, pi/2, pi]

print(np.sin(x))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


### 指数运算

In [12]:
x = np.array([1,2,3])

np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

### 对数运算

In [14]:
x = np.arange(1, 10)
x

print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


### 两个数组的运算

In [18]:
x1 = np.arange(1, 10)
x2 = np.arange(11, 20)
print(x1)
print(x2)

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [19]:
x1 + x2

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

## 矩阵运算

In [22]:
x = np.arange(0,10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 转置

In [24]:
x.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

### 矩阵乘法

注意和x1 * x2区别(对应元素相乘)

In [28]:
x1 = np.random.randint(0,10,size=(1,2))
x2 = np.random.randint(0,10,size=(2,1))

x1.dot(x2)

np.dot(x1, x2)

x2.dot(x1)

array([[12, 36],
       [15, 45]])

### 广播运算

**如果两个矩阵格式不满足, 会将维度为1的部分进行扩展, 扩展成为满足的情况.**

<img src="./pic/broadcast.png" width="400" height="400" />


In [29]:
x = np.array([0,1,2])
x + 5

array([5, 6, 7])

In [32]:
x1 = np.ones((3,3))
x2 = np.array([0,1,2])

x1 + x2

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [34]:
x1 = np.array([0,1,2]).reshape(3,1)
x2 = np.array([0,1,2])

x1 + x2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## 比较运算和掩码

### 比较运算

In [36]:
x = np.random.randint(0, 100, size=(4,4))
x

array([[62, 64, 93, 13],
       [89, 83, 89, 11],
       [83, 18, 20, 37],
       [28, 61, 95, 58]])

In [37]:
# 获取bool数组  逻辑运算符
x1 = (x > 50) & (x <100)
x1

array([[ True,  True,  True, False],
       [ True,  True,  True, False],
       [ True, False, False, False],
       [False,  True,  True,  True]])

In [38]:
# 统计数组中为True的个数
np.sum(x1)

10

In [31]:
# 统计全部元素是否满足某个规则
np.all(x>0)

True

In [32]:
# 统计是否有any元素满足规则
np.any(x==6)

False

In [33]:
# 按行判断, 是否每行的全部元素满足某个规则
np.all(x>50, axis=1) # 按列判断, axis=0

array([False,  True, False,  True])

In [34]:
# 按行判断, 是否某行的any元素满足某个条件
np.any(x>50, axis=1) # 按列判断, axis=0

array([ True,  True,  True,  True])

### 将bool数据作为索引, 返回相应的为True的数据

In [41]:
x = np.random.randint(10,100,(9,10))
x

array([[65, 38, 15, 46, 93, 83, 19, 39, 66, 97],
       [64, 61, 72, 98, 63, 20, 15, 65, 21, 98],
       [92, 78, 40, 52, 80, 31, 14, 15, 90, 23],
       [50, 90, 77, 35, 97, 22, 97, 28, 10, 26],
       [36, 17, 70, 12, 49, 22, 27, 78, 22, 81],
       [70, 28, 31, 41, 82, 96, 72, 95, 74, 37],
       [88, 62, 77, 29, 58, 82, 21, 78, 83, 57],
       [32, 11, 31, 66, 62, 18, 30, 98, 32, 57],
       [34, 88, 35, 94, 86, 12, 73, 81, 85, 91]])

In [42]:
# 获取x中>50的数据
x[ x>50 ]

array([65, 93, 83, 66, 97, 64, 61, 72, 98, 63, 65, 98, 92, 78, 52, 80, 90,
       90, 77, 97, 97, 70, 78, 81, 70, 82, 96, 72, 95, 74, 88, 62, 77, 58,
       82, 78, 83, 57, 66, 62, 98, 57, 88, 94, 86, 73, 81, 85, 91])

### 花哨的索引

#### 一维数组

In [43]:
x = np.arange(0, 10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
idx = np.array([0, 2, 4])
# x[idx] 的形式和idx一致, 这里x[idx]就是1-dim数组
x[idx]

array([0, 2, 4])

In [47]:
idx = np.array([
    [0, 2, 4], 
    [1, 3, 5]
])
# x[idx]的形式和idx一致, 这里x[idx]就是2-dim数组
x[idx]

array([[0, 2, 4],
       [1, 3, 5]])

#### 二维数组

In [52]:
x = np.random.randint(0, 20, (4,5))
x

array([[16, 15, 18,  1, 11],
       [ 1, 18, 13,  1, 17],
       [ 4, 19,  3,  9, 19],
       [10, 14, 11,  2,  8]])

In [56]:
# 获取元素 x[1][0] x[3][2]

idx_row = np.array([1, 3])
idx_col = np.array([0, 2])

x[idx_row, idx_col] 

array([ 1, 11])

In [60]:
# 获取每行的第1个和第3个元素

# 获取所有行
rows = x.shape[0]
idx_row = np.arange(rows)
idx_row_new = idx_row[:, np.newaxis] # 变成列向量

# 获取每列的第1, 第3元素
col_row = [0, 2]

x[idx_row_new, col_row]

array([[16, 18],
       [ 1, 13],
       [ 4,  3],
       [10, 11]])

## 通用运算

### 数值排序

In [69]:
x = np.random.randint(10,20,size=10)
x

array([15, 12, 19, 10, 13, 19, 19, 19, 19, 13])

In [70]:
# 产生副本
np.sort(x)

array([10, 12, 13, 13, 15, 19, 19, 19, 19, 19])

In [71]:
# 获取排序后的, 各个元素的索引信息
idx_sort = np.argsort(x)
idx_sort

array([3, 1, 4, 9, 0, 2, 5, 6, 7, 8])

In [72]:
# 改变原始数组x
x.sort()

### 最大最小值

In [73]:
np.max(x)

# index of max element
np.argmax(x)

5

In [75]:
np.min(x)
np.argmin(x)

0

### 求和, 求积

In [77]:
x = np.random.randint(10, 20, size=(3,4))
x

array([[13, 19, 19, 15],
       [15, 12, 18, 17],
       [17, 11, 14, 12]])

In [78]:
np.sum(x)

182

In [79]:
# 按行求和
np.sum(x, axis=1)

array([66, 62, 54])

In [80]:
# 按列求和
np.sum(x, axis=0)

array([45, 42, 51, 44])

In [81]:
# 求积
np.prod(x)

121811034945600