In [1]:
import numpy as np

# 从list创建数组

# 从列表list创建一维数组
x = np.array([1,2,3,4])
print(x)
print(x.shape)
print(type(x))
print(type(x[0]))
                            # [1 2 3 4]
                            # (4,)
                            # <class 'numpy.ndarray'>
                            # <class 'numpy.int64'>
                

# 指定数组元素数据类型 (numpy的数组的类型必须一致)
x = np.array([1,2,3,4], dtype="float32")
print(x)
print(x[0])
print(type(x[0]))
                            # [1. 2. 3. 4.]
                            # 1.0
                            # <class 'numpy.float32'>
            

# 从列表创建二维数组
x = np.array([
    [1,2],
    [3,4],
    [5,6]
])
print(x)
print(x.shape)
                            # [[1 2]
                            #  [3 4]
                            #  [5 6]]
                            # (3, 2)


[1 2 3 4]
(4,)
<class 'numpy.ndarray'>
<class 'numpy.int64'>
[1. 2. 3. 4.]
1.0
<class 'numpy.float32'>
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [7]:
import numpy as np

# 从无到有创建数组

# 创建长度为5, 值为0的数组
x = np.zeros(5, dtype=int)
print(x)
                                    # [0 0 0 0 0]

# 创建一个2*4的浮点型数组, 值都为1
x = np.ones((2, 4), dtype=float)
print(x)
                                    # [[1. 1. 1. 1.]
                                    #  [1. 1. 1. 1.]]
        
# 创建一个3*5的数组, 值都是8
x = np.full((3,5), 8)
print(x)
                                    # [[8 8 8 8 8]
                                    #  [8 8 8 8 8]
                                    #  [8 8 8 8 8]]
            
# 创建一个3*3的单位矩阵
x = np.eye(3)
print(x)
                                    # [[1. 0. 0.]
                                    #  [0. 1. 0.]
                                    #  [0. 0. 1.]]
            
# 创建一个线性的序列数组: 从1开始, 15结束, 步长为2
x = np.arange(1, 15, 2)
print(x)                            # [ 1  3  5  7  9 11 13]

# 创建一个等差数列: 4个元素, 将0-1等分成三份
x = np.linspace(0,1,4)
print(x)  
                                    # [0.         0.33333333 0.66666667 1.        ]
    
# 创建一个等比数列, 从10^0 - 10^9次方, 

[0 0 0 0 0]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1  3  5  7  9 11 13]
[0.         0.33333333 0.66666667 1.        ]
