In [1]:
import numpy as np

# 从list创建数组

# 从列表list创建一维数组
x = np.array([1,2,3,4])
print(x)
print(x.shape)
print(type(x))
print(type(x[0]))
                            # [1 2 3 4]
                            # (4,)
                            # <class 'numpy.ndarray'>
                            # <class 'numpy.int64'>
                

# 指定数组元素数据类型 (numpy的数组的类型必须一致)
x = np.array([1,2,3,4], dtype="float32")
print(x)
print(x[0])
print(type(x[0]))
                            # [1. 2. 3. 4.]
                            # 1.0
                            # <class 'numpy.float32'>
            

# 从列表创建二维数组
x = np.array([
    [1,2],
    [3,4],
    [5,6]
])
print(x)
print(x.shape)
                            # [[1 2]
                            #  [3 4]
                            #  [5 6]]
                            # (3, 2)


[1 2 3 4]
(4,)
<class 'numpy.ndarray'>
<class 'numpy.int64'>
[1. 2. 3. 4.]
1.0
<class 'numpy.float32'>
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [18]:
# 从无到有创建数组

import numpy as np


# 创建长度为5, 值为0的数组
x = np.zeros(5, dtype=int)
print(x)
                                    # [0 0 0 0 0]

# 创建一个2*4的浮点型数组, 值都为1
x = np.ones((2, 4), dtype=float)
print(x)
                                    # [[1. 1. 1. 1.]
                                    #  [1. 1. 1. 1.]]
        
# 创建一个3*5的数组, 值都是8
x = np.full((3,5), 8)
print(x)
                                    # [[8 8 8 8 8]
                                    #  [8 8 8 8 8]
                                    #  [8 8 8 8 8]]
            
# 创建一个3*3的单位矩阵
x = np.eye(3)
print(x)
                                    # [[1. 0. 0.]
                                    #  [0. 1. 0.]
                                    #  [0. 0. 1.]]
            
# 创建一个线性的序列数组: [1, 15), 步长为2
x = np.arange(1, 15, 2)
print(x)                            # [ 1  3  5  7  9 11 13]

# 创建一个等差数列: 4个元素, 将0-1等分成三份
x = np.linspace(0,1,4)
print(x)  
                                    # [0.         0.33333333 0.66666667 1.        ]
    
# 创建一个等比数列, 从10^0 - 10^9次方, 等比的产生10个数
x = np.logspace(0, 9, 10)
print(x)
                                    # [1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]
    
# 创建一个3*3数组, 元素为0-1之间的均匀分布的随机数
x = np.random.random((3,3))
print(x)
                                    # [[0.3478194  0.15451001 0.62584392]
                                    #  [0.51606038 0.896537   0.32470517]
                                    #  [0.75745009 0.09068659 0.61374355]]
            
# 创建一个3*3的数组, 元素为均值为0, 标准差为1的正态分布随机数
x = np.random.normal(0, 1, (3,3))
print(x)
                                    # [[-0.22689727  0.68675925  0.91156604]
                                    #  [ 0.57008821  0.74461085 -0.28911141]
                                    #  [ 0.22316875  0.67762701 -0.45709427]]
            
# 创建一个3*3的数组, 元素的取值是[0-10)的随机整数
np.random.randint(0, 10, (3, 3))
                                    # array([[0, 7, 0],
                                    #        [1, 2, 5],
                                    #        [4, 8, 8]])
            
# 将列表进行随机重排列
x = np.array([1,2,3,4])
np.random.permutation(x)
                                    # array([2, 1, 3, 4])
print(x)                            # [1 2 3 4] # permutation不会改变原数组


np.random.shuffle(x)
print(x)                            # [3 1 4 2] # shuffle会改变原数组


# 从数组中随机采样
x = np.arange(10, 25, dtype=float)
# 从1-D数组中进行采样, 采样4*3=12次, 构成一个4*3的数组
np.random.choice(x, size=(4,3))
                                    # array([[16., 13., 23.],
                                    #        [22., 23., 14.],
                                    #        [17., 24., 22.],
                                    #        [23., 18., 20.]])
# 针对1-D数组中的采样, 同时设置1-D数组中个元素的的采样概率
np.random.choice(x, size=(4, 3), p=x/np.sum(x))
                                    # array([[16., 15., 15.],
                                    #        [11., 22., 22.],
                                    #        [13., 20., 14.],
                                    #        [13., 22., 22.]])

[0 0 0 0 0]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1  3  5  7  9 11 13]
[0.         0.33333333 0.66666667 1.        ]
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]
[[0.45023075 0.42797194 0.75952574]
 [0.61510686 0.55722532 0.87802788]
 [0.703944   0.59819833 0.86758108]]
[[ 1.14898042  0.64243218 -1.0336328 ]
 [-1.46157684 -0.20168545 -1.17356936]
 [-0.16604111  0.87233415 -0.25929321]]
[1 2 3 4]
[1 2 4 3]


array([[16., 24., 16.],
       [14., 23., 19.],
       [16., 22., 17.],
       [15., 19., 22.]])